Remove Node from terms.jsonrc
sapegin/textlint-rule-terminology pull request #47
Opened 2022-07-22 15:55 UTC by Evilong

Node word is used widely in tons of different contexts, does't make much sense to infer that it is related with Node.js
Examples:
- Node as part of a graph
- Node as machine part of a cluster

2022-08-01 06:11 UTC, sapegin requested changes
We should still keep it to catch `node.js` and `nodejs`:

```js
["Node[ .]js", "Node.js"],
```

2022-08-01 15:03 UTC, Evilong commented
Changed as request by @sapegin

2022-08-02 07:34 UTC, sapegin commented
Thanks! Could you please update a failing test?

2022-08-02 07:35 UTC, sapegin approved these changes

2022-08-02 08:59 UTC, Evilong commented
done

2022-08-03 08:44 UTC, sapegin commented
It's still failing though...

2022-08-03 16:03 UTC, Evilong commented
I'm sorry, it is now fixed

2022-08-04 06:46 UTC, merged

2022-08-04 06:47 UTC, sapegin commented
:tada: This PR is included in version 3.0.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/textlint-rule-terminology/v/3.0.3)
- [GitHub release](https://github.com/sapegin/textlint-rule-terminology/releases/tag/v3.0.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: